
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor-sentinel
  namespace: my-namespace
  annotations:
    k8s.eip.work/workload: monitor-sentinel
    k8s.eip.work/displayName: 熔断及限流
    k8s.eip.work/service: ClusterIP
    k8s.eip.work/ingress: 'false'
  labels:
    k8s.eip.work/layer: monitor
    k8s.eip.work/name: monitor-sentinel
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s.eip.work/layer: monitor
      k8s.eip.work/name: monitor-sentinel
  template:
    metadata:
      labels:
        k8s.eip.work/layer: monitor
        k8s.eip.work/name: monitor-sentinel
    spec:
      containers:
      - name: monitor-sentinel
        image: eipwork/eip-monitor-sentinel:1.0.0

---
apiVersion: v1
kind: Service
metadata:
  name: monitor-sentinel
  namespace: my-namespace
  annotations:
    k8s.eip.work/workload: monitor-sentinel
    k8s.eip.work/displayName: 熔断及限流
  labels:
    k8s.eip.work/layer: monitor
    k8s.eip.work/name: monitor-sentinel
spec:
  type: ClusterIP
  ports:
  - port: 9701
    targetPort: 9701
  selector:
    k8s.eip.work/layer: monitor
    k8s.eip.work/name: monitor-sentinel

